apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogs-deployment
  labels:
    app: blogs
spec:
  replicas: {{ .Values.django.replicas }}
  selector:
    matchLabels:
      app: blogs
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: blogs
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox  
        command: ['sh', '-c', 'until nc -z postgresql-svc 5432; do sleep 1; done;']

      containers:
        - name: blogs-pod
          image: gcr.io/esoteric-sled-400504/blogs:v1
          envFrom:
            - configMapRef:
                name: blogs-config
          ports:
            - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: blogs-svc
spec:
  selector:
    app: blogs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
                              
