name: Build and Push
on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud 
        uses: 'google-github-actions/auth@v1'
        with: 
          credentials_json: ${{ secrets.GCP_CI_KEY }}
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Build docker image
        run: |
          docker build . -t gcr.io/esoteric-sled-400504/blogs:v1

      - name: configur docker client
        run: |
          gcloud auth configure-docker --quiet

      - name:
        run: |
          docker push gcr.io/esoteric-sled-400504/blogs:v1




